# Generated by Django 6.0.5 on 2026-05-08 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(default='image_converter', max_length=100)),
                ('original_format', models.CharField(max_length=10)),
                ('target_format', models.CharField(max_length=10)),
                ('original_size', models.PositiveIntegerField()),
                ('converted_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registo de conversão',
                'verbose_name_plural': 'Registos de conversões',
                'ordering': ['-created_at'],
            },
        ),
    ]
