# Generated by Django 6.0.5 on 2026-05-11 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='pdfs/originals/%Y/%m/')),
                ('edited_file', models.FileField(blank=True, null=True, upload_to='pdfs/edited/%Y/%m/')),
                ('name', models.CharField(max_length=255)),
                ('page_count', models.IntegerField(default=0)),
                ('size', models.BigIntegerField(default=0)),
                ('is_protected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento PDF',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MERGE', 'Fusão'), ('SPLIT', 'Divisão'), ('WATERMARK', 'Marca de Água'), ('PROTECT', 'Proteção'), ('REORDER', 'Reordenar')], max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='pdf_pro.pdfdocument')),
            ],
        ),
    ]
